### PR TITLE
New functions & validation function

### PR DESCRIPTION
**Pull request by ben-hearn-sb**
- Added new validate files under perforce root function that raises error if files not under root
- Removed default list arg for folder sync function
- Added a delete changelist function
- Added a revert changelist function (gets all files in a CL and reverts them all)

### CODE REVIEW

**Review by nielsvaes — CHANGES_REQUESTED** [review]
We shouldn't check if the file path is local before wrapping it in a P4File

**Review by nielsvaes — COMMENTED** [review]
problems with `files_to_p4files` outlined in other commit

**Comment by ben-hearn-sb** [comment]
Fixed error in checking file exists. What does this mean though

> "We shouldn't check if the file path is local before wrapping it in a P4File"

**Comment by nielsvaes** [comment]
> Fixed error in checking file exists. What does this mean though
> 
> > "We shouldn't check if the file path is local before wrapping it in a P4File"

In `files_to_p4files` you do

```
            if not os.path.exists(fpath):
                logging.info(f'{fpath} does not exist on disk. Cannot create p4 file object from it')
                file_list.append(fpath)
```
However, you can also pass in depot paths to that function in which case `os.path.exists` will always fail

**Comment by ben-hearn-sb** [comment]
Ok that makes sense, I have amended it so we get local file paths first

**Comment by ben-hearn-sb** [comment]
Can we get this package bumped on pip btw when it gets merged next

**Pull request merged**
